apiVersion: v1
kind: Pod
metadata:
  name: busybox-pod
  labels:
    env: test
spec:
  containers:
  - name: busybox-container
    image: busybox
    command: ["sleep", "3600"]
    resources:
      limits:
        cpu: "1"
        memory: "200Mi"
