apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: busybox-replicaset
spec:
  selector:
    matchLabels:
      env: test  
  replicas: 3
  template:
    metadata:
      name: busybox-pod
      labels:
        env: test
    spec:
      containers:
      - name: busybox-container
        image: busybox
        command: ["sleep", "3600"]
        resources:
          limits:
            cpu: "1"
            memory: "200Mi"
    
